import{a as w,S as L,i as c}from"./assets/vendor-u8rapaCG.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function v(r,o,n){const a=new URLSearchParams({key:"46126545-8899f9a6fbc888edd135bf332",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:n,page:o});return(await w.get(`https://pixabay.com/api/?${a}`)).data.hits}function q(r){const o=r.map(n=>{const{largeImageURL:a,webformatURL:e,tags:t,likes:i,views:f,comments:h,downloads:b}=n;return`
            <li class="gallery-item">
                <a href="${a}" class="gallery-item">
                    <img src="${e}" alt="${t}" />
                    <div class="image-info">
                        <p>Likes: ${i}</p>
                        <p>Views: ${f}</p>
                        <p>Comments: ${h}</p>
                        <p>Downloads: ${b}</p>
                    </div>
                </a>
            </li>`}).join("");u.insertAdjacentHTML("beforeend",o)}const p=document.querySelector(".search-form"),u=document.querySelector(".image-gallery"),s=document.querySelector(".load-more"),y=document.querySelector(".loader");let S=new L(".image-gallery a",{captionsData:"alt",captionDelay:250}),l=1,d=15,m="";const P=Math.ceil(500/d);p.addEventListener("submit",async r=>{r.preventDefault();const o=p.elements.query.value.trim();if(!o){c.show({message:"Please enter a search query.",color:"red",position:"topRight"}),s.style.display="none";return}m=o,l=1,u.innerHTML="",s.style.display="none",g()});async function g(){y.style.display="block";try{const r=await v(m,l,d);if(r.length===0&&l===1){c.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),u.innerHTML="",s.style.display="none";return}q(r),S.refresh(),R(),r.length<d||l>=P?(s.style.display="none",c.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"})):s.style.display="block"}catch{c.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"}),s.style.display="none"}finally{y.style.display="none"}}s.addEventListener("click",()=>{l+=1,s.style.display="none",g()});function R(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
