import{a as w,S as L,i as c}from"./assets/vendor-u8rapaCG.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function v(o,r,a){try{return(await w.get("https://pixabay.com/api/?",{params:{key:"46126545-8899f9a6fbc888edd135bf332",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:a,page:r}})).data.hits}catch(s){throw console.error(s),s}}function q(o){const r=o.map(a=>{const{largeImageURL:s,webformatURL:e,tags:t,likes:i,views:g,comments:h,downloads:b}=a;return`
            <li class="gallery-item">
                <a href="${s}" class="gallery-item">
                    <img src="${e}" alt="${t}" />
                    <div class="image-info">
                        <p>Likes: ${i}</p>
                        <p>Views: ${g}</p>
                        <p>Comments: ${h}</p>
                        <p>Downloads: ${b}</p>
                    </div>
                </a>
            </li>`}).join("");u.insertAdjacentHTML("beforeend",r)}const d=document.querySelector(".search-form"),u=document.querySelector(".image-gallery"),l=document.querySelector(".load-more"),m=document.querySelector(".loader");let S=new L(".image-gallery a",{captionsData:"alt",captionDelay:250}),n=1,p=15,y="";const P=Math.ceil(500/p);d.addEventListener("submit",async o=>{o.preventDefault();const r=d.elements.query.value.trim();if(!r){c.show({message:"Please enter a search query.",color:"red",position:"topRight"});return}y=r,n=1,u.innerHTML="",f()});async function f(){m.style.display="block";try{const o=await v(y,n,p);if(o.length===0&&n===1){c.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),u.innerHTML="";return}q(o),S.refresh(),R(),n<P?l.style.display="block":(l.style.display="none",c.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"}))}catch{c.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"})}finally{m.style.display="none"}}l.addEventListener("click",()=>{n+=1,f()});function R(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
