import{a as w,S as L,i as c}from"./assets/vendor-u8rapaCG.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function v(o,r,n){const a=new URLSearchParams({key:"46126545-8899f9a6fbc888edd135bf332",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:n,page:r});return(await w.get(`https://pixabay.com/api/?${a}`)).data.hits}function q(o){const r=o.map(n=>{const{largeImageURL:a,webformatURL:e,tags:t,likes:i,views:g,comments:h,downloads:b}=n;return`
            <li class="gallery-item">
                <a href="${a}" class="gallery-item">
                    <img src="${e}" alt="${t}" />
                    <div class="image-info">
                        <p>Likes: ${i}</p>
                        <p>Views: ${g}</p>
                        <p>Comments: ${h}</p>
                        <p>Downloads: ${b}</p>
                    </div>
                </a>
            </li>`}).join("");d.insertAdjacentHTML("beforeend",r)}const u=document.querySelector(".search-form"),d=document.querySelector(".image-gallery"),s=document.querySelector(".load-more"),p=document.querySelector(".loader");let S=new L(".image-gallery a",{captionsData:"alt",captionDelay:250}),l=1,y=15,m="";const P=Math.ceil(500/y);u.addEventListener("submit",async o=>{o.preventDefault();const r=u.elements.query.value.trim();if(!r){c.show({message:"Please enter a search query.",color:"red",position:"topRight"}),s.style.display="none";return}m=r,l=1,d.innerHTML="",s.style.display="none",f()});async function f(){p.style.display="block";try{const o=await v(m,l,y);if(o.length===0&&l===1){c.show({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"topRight"}),d.innerHTML="",s.style.display="none";return}q(o),S.refresh(),R(),l<P?s.style.display="block":(c.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"}),s.style.display="none")}catch{c.show({message:"We're sorry, but you've reached the end of search results.",color:"red",position:"topRight"}),s.style.display="none"}finally{p.style.display="none"}}s.addEventListener("click",()=>{l+=1,s.style.display="none",f()});function R(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
